-- Insert missing and default resources into vibe_resources
INSERT INTO vibe_resources (title, description, url, category, tags, provider, rating, icon_text, created_at) VALUES 
('Public APIs', '개발에 필요한 공개 API들의 방대한 모음집', 'https://public-apis.io', 'API', 'API,OpenData', 'PublicAPIs', 4.6, 'API', CURRENT_TIMESTAMP),
('Google Fonts', '무료로 사용 가능한 웹 폰트 라이브러리', 'https://fonts.google.com', '웹사이트', 'Font,Design', 'Google', 4.9, 'Font', CURRENT_TIMESTAMP),
('Claude AI', 'Anthropic의 고성능 대화형 AI 모델', 'https://claude.ai', 'AI도구', 'AI,Claude', 'Anthropic', 4.8, 'AI', CURRENT_TIMESTAMP),
('W3Schools', '웹 기술의 기초를 배우기에 좋은 튜토리얼 사이트', 'https://w3schools.com', '웹사이트', 'Study,Web', 'W3Schools', 4.4, 'W3S', CURRENT_TIMESTAMP),
('GitHub Desktop', 'CLI 없이 Git을 편리하게 사용하는 GUI 도구', 'https://desktop.github.com', '개발도구', 'Git,Tool', 'GitHub', 4.7, 'Git', CURRENT_TIMESTAMP),
('Gabia 도메인', '국내 최대 도메인 및 호스팅 서비스', 'https://gabia.com', '도메인', 'Domain,Korea', 'Gabia', 4.3, 'Gab', CURRENT_TIMESTAMP),
('하이드레이션 불일치(Hydration Mismatch) 완벽 가이드', '### 🌊 하이드레이션 불일치(Error #418) 원인과 해결법\n\nNext.js나 React SSR 환경에서 가장 자주 발생하는 **Hydration Mismatch**는 서버에서 렌더링한 HTML과 브라우저에서 처음 렌더링한 결과가 다를 때 발생합니다.\n\n---\n\n#### 1. 대표적인 원인\n1. **비결정적 데이터 사용**: `new Date()`, `Math.random()` 등을 컴포넌트 본문에서 직접 호출하는 경우.\n2. **브라우저 전용 API 접근**: `useEffect` 밖에서 `window`, `localStorage`, `sessionStorage`를 사용하는 경우.\n3. **지역별 포맷 차이**: `toLocaleString()` 처럼 서버와 클라이언트의 시간대/언어 설정에 따라 결과가 달라지는 함수 사용.\n4. **잘못된 HTML 구조**: `<a>` 태그 안에 `<a>`를 넣거나, `<p>` 태그 안에 `<div>`를 넣는 등 문법 오류.\n\n#### 2. 확실한 해결 방법\n\n**A. `mounted` 상태 활용 (권장)**\n컴포넌트가 클라이언트에 마운트된 이후에만 동적 데이터를 그리도록 제한합니다.\n```tsx\nconst [mounted, setMounted] = useState(false);\nuseEffect(() => setMounted(true), []);\n\nreturn <div>{mounted ? localStorage.getItem(\"data\") : \"Loading...\"}</div>;\n```\n\n**B. `suppressHydrationWarning` 사용**\n텍스트가 미세하게 다를 수밖에 없는 경우(예: 다크모드 클래스, 단순 연도 등) 속성을 통해 경고를 무시합니다.\n```tsx\n<html suppressHydrationWarning>\n```\n\n**C. `useEffect` 내에서 데이터 갱신**\n초기 상태는 서버와 동일하게 고정값(예: 2026)으로 두고, 마운트 직후 실제 데이터로 업데이트합니다.\n\n#### 3. 주의사항\n- 하이드레이션 에러는 단순 경고가 아닙니다. 이 에러가 발생하면 React는 전체 DOM을 새로 그리게 되어 **성능 저하**와 **이벤트 바인딩 오류**를 유발할 수 있습니다.\n- 모든 동적 요소는 반드시 클라이언트 사이드 마운트 이후에 결정되도록 설계하세요.', '#', '문서/가이드', 'Hydration,Next.js,React,ErrorFix', 'Vibe', 5.0, 'HYD', '2026-05-05'),
('서버 정보 및 관리 보안 가이드', '### 🔐 서버 정보 및 관리자 계정 보안 관리 가이드\n\n현대적인 웹 개발 환경에서 민감한 정보를 안전하게 관리하는 것은 프로젝트의 생존과 직결됩니다. 특정 플랫폼에 종속되지 않는 보편적인 보안 관리 원칙을 정리합니다.\n\n---\n\n#### 1. 환경 변수(Environment Variables) 활용\n가장 기본적인 원칙은 **\"코드는 공개되어도 정보는 비공개여야 한다\"**는 것입니다.\n- **절대 하드코딩 금지**: API 키, DB 접속 정보 등을 코드에 직접 쓰지 마세요.\n- **.env 파일 분리**: 개발 환경에서는 `.env` 파일을 사용하고, 이 파일은 반드시 `.gitignore`에 등록하여 Git 저장소에서 제외해야 합니다.\n- **플랫폼 시크릿 매니저**: 배포 환경(Cloudflare, Vercel, AWS 등)에서 제공하는 전용 환경 변수 관리 도구를 사용하세요.\n\n#### 2. 서비스 계정 및 비밀 파일 처리\nFCM이나 Google Cloud의 JSON 키 파일과 같이 파일 형태의 보안 정보가 필요한 경우:\n- **문자열화(Stringify)**: 파일 내용을 JSON 문자열로 변환하여 환경 변수에 저장하고, 필요할 때 코드에서 `JSON.parse()`로 읽어 사용하세요.\n- **보안 금고(Vault)**: 대규모 프로젝트라면 HashiCorp Vault나 AWS Secrets Manager 같은 전문 도구 도입을 검토하세요.\n\n#### 3. 관리자 계정 및 접근 제어\n- **최소 권한의 원칙(Least Privilege)**: 관리자 계정이라도 필요한 권한만 부여하세요. 모든 권한을 가진 Root 계정은 가급적 일상 작업에 쓰지 않습니다.\n- **2단계 인증(2FA/MFA) 필수**: 관리 대시보드나 서버 접근 시 Google Authenticator 등을 통한 2차 인증을 반드시 활성화하세요.\n- **IP 화이트리스팅**: 관리자 페이지는 사내 IP나 특정 VPN 환경에서만 접근할 수 있도록 제한하는 것이 안전합니다.\n\n#### 4. 정기적인 키 갱신(Rotation)\n- **유효 기간 설정**: API 키나 비밀번호는 유출 여부와 관계없이 정기적(예: 3개월)으로 갱신하는 습관을 들이세요.\n- **퇴사자 처리**: 팀원이 프로젝트를 떠날 경우 즉시 모든 접근 권한을 회수하고 필요한 경우 키를 재발급하세요.\n\n#### 5. 감사 로그(Audit Logs) 확인\n- **누가, 언제, 무엇을 했는가?**: 시스템 설정 변경이나 민감 데이터 접근 기록을 남기고 정기적으로 모니터링하세요. 이상 징후를 조기에 발견하는 핵심입니다.', '#', '문서/가이드', 'Security,DevOps,Admin', 'Vibe', 5.0, 'SEC', '2026-05-05'),
('기타 유용한 사이트 모음', '여러 카테고리에 속하지 않는 유용한 유틸리티 모음', '#', '기타', 'Misc,Utils', 'Vibe', 4.0, 'Etc', CURRENT_TIMESTAMP);
