INSERT INTO vibe_resources (title, description, url, category, tags, provider, rating, icon_text, created_at) VALUES 
('MDN Web Docs', '웹 개발을 위한 종합 문서. HTML, CSS, JS 가이드 제공', 'https://developer.mozilla.org', '문서/가이드', 'HTML,CSS,JS', 'Mozilla', 4.9, 'MDN', CURRENT_TIMESTAMP),
('React 공식 문서', 'React 공식 홈. 최신 기능 가이드 제공', 'https://react.dev', '문서/가이드', 'Frontend,React', 'Meta', 4.8, 'React', CURRENT_TIMESTAMP),
('Tailwind CSS', '유틸리티 퍼스트 CSS 프레임워크 공식 문서', 'https://tailwindcss.com', '개발도구', 'CSS,Tailwind', 'Tailwind Labs', 4.7, 'TW', CURRENT_TIMESTAMP),
('Figma', '인터랙티브 디자인 및 프로토타이핑 도구', 'https://figma.com', '디자인/UX', 'Design,UI', 'Figma', 4.8, 'Fig', CURRENT_TIMESTAMP),
('ChatGPT', 'AI 기반 대화형 모델 및 프롬프트 서비스', 'https://chat.openai.com', 'AI도구', 'AI,LLM', 'OpenAI', 4.9, 'GPT', CURRENT_TIMESTAMP),
('Vercel', 'Next.js 최적화 배포 및 호스팅 플랫폼', 'https://vercel.com', '배포/운영', 'Cloud,Hosting', 'Vercel', 4.8, 'Ver', CURRENT_TIMESTAMP),
('Supabase', '오픈소스 Firebase 대안 데이터베이스 플랫폼', 'https://supabase.com', 'API', 'DB,Backend', 'Supabase', 4.7, 'Supa', CURRENT_TIMESTAMP),
('Namecheap', '합리적인 가격의 도메인 등록 및 관리 서비스', 'https://namecheap.com', '도메인', 'Domain,Infra', 'Namecheap', 4.5, 'Name', CURRENT_TIMESTAMP),
('Visual Studio Code', '가장 인기 있는 오픈소스 코드 에디터', 'https://code.visualstudio.com', '개발도구', 'Editor,IDE', 'Microsoft', 4.9, 'VS', CURRENT_TIMESTAMP),
('Public APIs', '개발에 필요한 공개 API들의 방대한 모음집', 'https://public-apis.io', 'API', 'API,OpenData', 'PublicAPIs', 4.6, 'API', CURRENT_TIMESTAMP),
('Google Fonts', '무료로 사용 가능한 웹 폰트 라이브러리', 'https://fonts.google.com', '웹사이트', 'Font,Design', 'Google', 4.9, 'Font', CURRENT_TIMESTAMP),
('Claude AI', 'Anthropic의 고성능 대화형 AI 모델', 'https://claude.ai', 'AI도구', 'AI,Claude', 'Anthropic', 4.8, 'AI', CURRENT_TIMESTAMP),
('W3Schools', '웹 기술의 기초를 배우기에 좋은 튜토리얼 사이트', 'https://w3schools.com', '웹사이트', 'Study,Web', 'W3Schools', 4.4, 'W3S', CURRENT_TIMESTAMP),
('GitHub Desktop', 'CLI 없이 Git을 편리하게 사용하는 GUI 도구', 'https://desktop.github.com', '개발도구', 'Git,Tool', 'GitHub', 4.7, 'Git', CURRENT_TIMESTAMP),
('Gabia 도메인', '국내 최대 도메인 및 호스팅 서비스', 'https://gabia.com', '도메인', 'Domain,Korea', 'Gabia', 4.3, 'Gab', CURRENT_TIMESTAMP);
